/**
 * Build script for Vercel serverless function.
 * Bundles server/vercel-entry.ts into api/index.mjs with all path aliases resolved.
 */
import { build } from "esbuild";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");

await build({
  entryPoints: [path.resolve(projectRoot, "server/vercel-entry.ts")],
  bundle: true,
  platform: "node",
  target: "node20",
  format: "esm",
  outfile: path.resolve(projectRoot, "api/index.mjs"),
  // Externalize node_modules packages (they'll be installed by Vercel)
  packages: "external",
  // Resolve path aliases
  alias: {
    "@shared": path.resolve(projectRoot, "shared"),
    "@": path.resolve(projectRoot, "client/src"),
  },
  // Don't bundle these - they're available as node_modules on Vercel
  external: [
    "dotenv",
    "express",
    "@trpc/server",
    "@supabase/supabase-js",
    "cookie",
    "jose",
    "axios",
    "zod",
    "superjson",
    "nanoid",
  ],
  // Ensure .ts files are handled
  loader: {
    ".ts": "ts",
  },
  // Source map for debugging
  sourcemap: false,
  // Minify for smaller bundle
  minify: false,
  // Banner to mark this as auto-generated
  banner: {
    js: "// Auto-generated by scripts/build-vercel.mjs - DO NOT EDIT\n",
  },
});

console.log("✅ Vercel serverless function built: api/index.mjs");
